import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className="flexCenter">
      <body className="relative h-svh w-full min-w-[320px] max-w-[450px] overflow-y-scroll border-x px-4">
        {children}
      </body>
    </html>
  )
}
