import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { cookies } from 'next/headers'
import DarkMode from './DarkMode'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  const cookie = cookies().get('mode')


  console.log(session) // 로그인 정보 출력
  return (
    <html lang="ko">
      <body className={
        cookie != undefined && cookie.value == 'dark' 
          ? 'dark-mode'
          : ''
      }>
      <div className="navbar"> 
        <Link href="/" className="logo">Appleforum</Link> 
        <Link href="/list">List</Link>
        <LoginBtn />
        <DarkMode />
      </div>  
        {children}
      </body>
    </html>
  )
}
